spring:
  datasource:
    url: "jdbc:mysql://localhost/board"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
